# Generated by Django 4.2.20 on 2025-11-26 19:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hard_skills_summary', models.TextField(help_text='Обобщенная информация о технических навыках кандидата', verbose_name='Суммированные хард скилы')),
                ('theoretical_test_summary', models.TextField(help_text='Обобщенные результаты теоретических тестов и вопросов', verbose_name='Суммированные результаты теоретического тестирования')),
                ('practical_test_summary', models.TextField(help_text='Обобщенные результаты практических заданий и написания кода', verbose_name='Суммированные результаты практического тестирования')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('candidate_name', models.CharField(blank=True, help_text='Имя кандидата (опционально)', max_length=200, null=True, verbose_name='Имя кандидата')),
            ],
            options={
                'verbose_name': 'Рапорт',
                'verbose_name_plural': 'Рапорты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Краткое название задачи', max_length=200, verbose_name='Название задачи')),
                ('description', models.TextField(help_text='Полное описание задачи, условия, требования', verbose_name='Описание')),
                ('examples', models.JSONField(blank=True, default=list, help_text="Примеры ввода и вывода в формате JSON: [{'input': '...', 'output': '...'}]", verbose_name='Примеры')),
                ('tests', models.JSONField(blank=True, default=list, help_text="Тестовые случаи в формате JSON: [{'input': [...], 'expected': '...'}]", verbose_name='Тесты')),
                ('max_execution_time', models.FloatField(default=5.0, help_text='Максимальное время выполнения программы в секундах', validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Максимальное время выполнения (секунды)')),
                ('max_memory_mb', models.IntegerField(default=512, help_text='Максимальный объем памяти в мегабайтах', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Максимальная память (МБ)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, help_text='Показывать ли задачу пользователям', verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'ordering': ['-created_at'],
            },
        ),
    ]
