# Generated by Django 4.2.20 on 2025-11-26 20:43

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(help_text='Уникальный никнейм пользователя', max_length=150, unique=True, verbose_name='Никнейм')),
                ('role', models.CharField(choices=[('HR', 'HR'), ('CANDIDATE', 'Кандидат')], help_text='Роль пользователя: HR или Кандидат', max_length=20, verbose_name='Роль')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Краткое название задачи', max_length=200, verbose_name='Название задачи')),
                ('description', models.TextField(help_text='Полное описание задачи, условия, требования', verbose_name='Описание')),
                ('examples', models.JSONField(blank=True, default=list, help_text="Примеры ввода и вывода в формате JSON: [{'input': '...', 'output': '...'}]", verbose_name='Примеры')),
                ('tests', models.JSONField(blank=True, default=list, help_text="Тестовые случаи в формате JSON: [{'input': [...], 'expected': '...'}]", verbose_name='Тесты')),
                ('max_execution_time', models.FloatField(default=5.0, help_text='Максимальное время выполнения программы в секундах', validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Максимальное время выполнения (секунды)')),
                ('max_memory_mb', models.IntegerField(default=512, help_text='Максимальный объем памяти в мегабайтах', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Максимальная память (МБ)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, help_text='Показывать ли задачу пользователям', verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hard_skills_summary', models.TextField(help_text='Обобщенная информация о технических навыках кандидата', verbose_name='Суммированные хард скилы')),
                ('theoretical_test_summary', models.TextField(help_text='Обобщенные результаты теоретических тестов и вопросов', verbose_name='Суммированные результаты теоретического тестирования')),
                ('practical_test_summary', models.TextField(help_text='Обобщенные результаты практических заданий и написания кода', verbose_name='Суммированные результаты практического тестирования')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('candidate', models.ForeignKey(help_text='Кандидат, который прошел тестирование', limit_choices_to={'role': 'CANDIDATE'}, on_delete=django.db.models.deletion.CASCADE, related_name='reports_as_candidate', to=settings.AUTH_USER_MODEL, verbose_name='Кандидат')),
                ('hr', models.ForeignKey(help_text='HR, к которому идет кандидат', limit_choices_to={'role': 'HR'}, on_delete=django.db.models.deletion.CASCADE, related_name='reports_as_hr', to=settings.AUTH_USER_MODEL, verbose_name='HR')),
            ],
            options={
                'verbose_name': 'Рапорт',
                'verbose_name_plural': 'Рапорты',
                'ordering': ['-created_at'],
            },
        ),
    ]
