# Generated by Django 4.2.20 on 2025-11-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='suspicious_activity_summary',
            field=models.TextField(blank=True, default='', help_text='Обобщенная информация о подозрительной активности кандидата (копипаст, использование ИИ и т.д.)', verbose_name='Суммированная подозрительная активность'),
        ),
    ]
