# Generated by Django 4.2.25 on 2025-11-27 00:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codeapp', '0003_user_ban_reason_user_banned_at_user_is_banned'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(default='init', help_text='Текущая стадия интервью: init, hard_desc, theory, finished', max_length=50, verbose_name='Стадия')),
                ('hard_desc', models.TextField(blank=True, help_text='Описание технических навыков кандидата', null=True, verbose_name='Описание навыков')),
                ('theory_questions', models.JSONField(blank=True, default=list, help_text='Список теоретических вопросов', verbose_name='Теоретические вопросы')),
                ('current_question_idx', models.IntegerField(default=0, help_text='Индекс текущего вопроса в списке', verbose_name='Текущий индекс вопроса')),
                ('chat_history', models.JSONField(blank=True, default=list, help_text='История сообщений интервью в формате JSON', verbose_name='История чата')),
                ('terminated', models.BooleanField(default=False, help_text='Было ли интервью прервано из-за плохого поведения', verbose_name='Прервано')),
                ('termination_reason', models.TextField(blank=True, help_text='Причина прерывания интервью', null=True, verbose_name='Причина прерывания')),
                ('awaiting_hint_answer', models.BooleanField(default=False, help_text='Ожидается ли ответ на наводящий вопрос', verbose_name='Ожидается ответ на наводящий вопрос')),
                ('current_hint', models.TextField(blank=True, help_text='Текущий наводящий вопрос, если есть', null=True, verbose_name='Текущий наводящий вопрос')),
                ('theory_completed', models.BooleanField(default=False, help_text='Завершена ли теоретическая часть интервью', verbose_name='Теория завершена')),
                ('interview_started', models.BooleanField(default=False, help_text='Начато ли интервью', verbose_name='Интервью начато')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(help_text='Кандидат, проходящий интервью', limit_choices_to={'role': 'CANDIDATE'}, on_delete=django.db.models.deletion.CASCADE, related_name='interview_session', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сессия интервью',
                'verbose_name_plural': 'Сессии интервью',
                'ordering': ['-updated_at'],
            },
        ),
    ]
